=== mvsframework/mvs/src/core/XSD/sai.xsd
<!--
  
   Copyright © 2015 Claus Christmann <hcc |ä| gatech.edu>.
   
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
   
   http://www.apache.org/licenses/LICENSE-2.0
   
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

-->

<?xml version="1.0" encoding="ISO-8859-1"?>
<schema 
  xmlns="http://www.w3.org/2001/XMLSchema" 
  xmlns:sai="http://uav.ae.gatech.edu/XML/SAI" 
  targetNamespace="http://uav.ae.gatech.edu/XML/SAI" 
  elementFormDefault="qualified" 
>
<!--<import namespace="http://www.omg.org/IDL-Mapped/" schemaLocation="settings.xsd"/>-->

<!--  Dedicated Type Declarations -->

<simpleType name="RawAxisValue_t">
    <restriction base="integer">
      <minInclusive value="-32786"/>
      <maxInclusive value="32786"/>
    </restriction>
</simpleType>

<complexType name="AxisMapping_t">
  <sequence>
    <element name="axis"    type="nonNegativeInteger" />
    <element name="reverse" type="boolean" default="true"   minOccurs="0" /> <!-- default value is true, allowing to simply put a <reverse /> in the axis to enable axis reversal-->
    <element name="max"     type="sai:RawAxisValue_t" default="32786"  />
    <element name="center"  type="sai:RawAxisValue_t" default="0"      minOccurs="0"/>
    <element name="min"     type="sai:RawAxisValue_t" default="-32786" />
    <element name="deadband" type="nonNegativeInteger"      minOccurs="0" />
    <element name="sensitivity" type="nonNegativeInteger"   minOccurs="0" />
  </sequence>
</complexType>

<simpleType name="ButtonAction_t">
  <restriction base="string">
    <enumeration value="inop" />
    <enumeration value="dash" />
    <enumeration value="extremes" />
    <enumeration value="altitudeHold" />
  </restriction>
</simpleType>

<complexType name="ButtonMapping_t">
  <simpleContent>
    <extension base="nonNegativeInteger">
      <attribute name="action" type="sai:ButtonAction_t" use="required" />
    </extension>
  </simpleContent>
</complexType>

<complexType name="Joystick_t">
  <sequence>
    <element name="name"      type="string"/>
    <element name="Roll"      type="sai:AxisMapping_t" />
    <element name="Pitch"     type="sai:AxisMapping_t" />
    <element name="Yaw"       type="sai:AxisMapping_t" />
    <element name="Throttle"  type="sai:AxisMapping_t" />
    <element name="Aux"       type="sai:AxisMapping_t"   minOccurs="0" maxOccurs="2" />  
    <element name="button"    type="sai:ButtonMapping_t" minOccurs="0" maxOccurs="16" />
    <element name="autoRepeatDelay" type="nonNegativeInteger" default="250" minOccurs="0"/>
  </sequence>
  <attribute name="id" type="nonNegativeInteger" />
</complexType>

<complexType name="Lens_t">
  <sequence>
    <!-- horizontal Field-of-View -->
    <element name="hFov" type="nonNegativeInteger" default="80" />
    <!-- vertical Feild-of-View -->
    <!--<element name="vFov" type="nonNegativeInteger" default="60" />-->
  </sequence>
</complexType>

<simpleType name="Coordinates_t">
  <list itemType="string"/>
</simpleType>

<simpleType name="KmlLink_t">
  <restriction base="string" />
</simpleType>

<complexType name="Point_t">
  <sequence>
    <element name="coordinates" type="sai:Coordinates_t" />
  </sequence>
</complexType>

<complexType name="Polygon_t">
  <sequence>
    <element name="coordinates" type="sai:Coordinates_t" />
  </sequence>
</complexType>

<complexType name="Frame_t">
  <choice>
    <element name="href"   type="sai:KmlLink_t" />
    <element name="coordinates" type="sai:Coordinates_t" />
  </choice>
</complexType>

<complexType name="Arena_t">
  <choice>
    <element name="href"   type="sai:KmlLink_t" />
    <element name="coordinates" type="sai:Coordinates_t" />
  </choice>
</complexType>

<complexType name="ObstacleDatabase_t">
  <sequence>
    <element name="href"   type="sai:KmlLink_t" />
  </sequence>
</complexType>   




<!-- Dealing with SimItem Types
  =============================
-->

<complexType name="SimItem_t" abstract="true" >
  <sequence>
    <element name="name" type="string" default="(SimItem)"/>
  </sequence>
</complexType>
 
<complexType name="Datalink_t">
  <complexContent>
    <extension base="sai:SimItem_t" />
  </complexContent>
</complexType>
 
<complexType name="GenericNode_t">
  <complexContent>
    <extension base="sai:SimItem_t">
      <sequence>
        <element name="coordinates" type="sai:Coordinates_t" />
        <!-- Time between initialization and starting, in [ms] -->
        <element name="startupDelay" type="nonNegativeInteger" minOccurs="0" maxOccurs="1" /> 
        <!-- The datalink interface -->
        <element name="dds" type="sai:Datalink_t" minOccurs="0" maxOccurs="1"  />
        <element name="camera" type="sai:Lens_t" minOccurs="0" maxOccurs="1"  />
      </sequence>
    </extension>
  </complexContent>
</complexType>

<complexType name="GustInterface_t">
  <complexContent>
    <extension base="sai:SimItem_t">
    <sequence>
      <element name="gustIp"       type="string" />
      <element name="gustUdpPort"  type="nonNegativeInteger" />
      <element name="localIp"      type="string" />
      <element name="localUdpPort" type="nonNegativeInteger" />
      <element name="inpFilePath"  type="string" minOccurs="0" maxOccurs="1" />
      
      <!-- TODO: Make the interface to setting ESIM variables more generic!
      It would be cool if instead of making an entry for every ESIM parameter 
      we could use stuff like this:
        <group name="manAugment">
          <parameter name="anom">30</parameter>
        </group>
      But this would require a more elborate parser on the C side to get the 
      name attribute and then create the proper 
      "rc <group.name>.<parameter.name>=value" command for esim.
      -->
      <element name="manAugment" >
        <complexType>
          <sequence>
            <element name="anom"      type="decimal" default="30"/>
            <element name="jerk"      type="decimal" default="20"/>
            <element name="vcHzGo"    type="decimal" default="10"/>
            <element name="vcHzStop"  type="decimal" default="20"/>
            <element name="vcHzSide"  type="decimal" default="5"/>
          </sequence>
        </complexType>
      </element>
      <element name="params_mr" >
        <complexType>
          <sequence>
            <element name="damp" type="decimal" default="0.5" />
          </sequence>
        </complexType>
      </element>

    </sequence>
  </extension>
  </complexContent>
</complexType>
 

<complexType name="HumanMachineInterface_t">
  <complexContent>
    <extension base="sai:SimItem_t">
    <sequence>
      <element name="Joystick" type="sai:Joystick_t" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
    </extension>
  </complexContent>
</complexType>
 

<!-- Dealing with the Node Types
  ==============================
  There are currently two types of nodes: UAVs and Control Stations.
  The GenericNode_t serves as a base class type for both, used with the 
  extension element in the specific derived types. 
  This requires tp set the 'generate-polymorphic' switch in CodeSynthesis XSD.
-->


<complexType name="GustUavNode_t" >
  <complexContent>
    <extension base="sai:GenericNode_t">
      <sequence>
        <element name="gust" type="sai:GustInterface_t" />
      </sequence>
    </extension>
  </complexContent>
</complexType>

<complexType name="UavNode_t" >
  <complexContent>
    <extension base="sai:GustUavNode_t" />
  </complexContent>
</complexType>

<complexType name="ControlStationNode_t" >
  <complexContent>
    <extension base="sai:GenericNode_t">
      <sequence>
        <element name="hmi" type="sai:HumanMachineInterface_t" />
      </sequence>
    </extension>
  </complexContent>
</complexType>

<!-- Creating the NodeGroup_t and its elements
  ============================================
  As these are global root elements (direct children of <schema>, it is 
  necessary to set the 'root-element-last' or 'root-elemet <type>' flags with 
  CodeSynthesis XSD.
-->
<element name="AbstractSimItem" type="sai:SimItem_t" abstract="true" /> 
<element name="AbstractNode"    type="sai:GenericNode_t" abstract="true" /> 
<element name="UAV"             type="sai:UavNode_t"            substitutionGroup="sai:AbstractNode" />
<element name="ControlStation"  type="sai:ControlStationNode_t" substitutionGroup="sai:AbstractNode" />

<complexType name="NodeGroup_t">
  <sequence>
    <element ref="sai:AbstractNode" minOccurs="0" maxOccurs="unbounded" />
  </sequence>
</complexType>  

<!--  The actual root element of this schema
  ==========================================
  Make sure that this element is the last global root element declared. This is
  necessary to make the XSD switch 'root-element-last' work.
-->
<element name="Configuration">
  <complexType>
    <sequence>
      
      <element name="DatumNED"   type="sai:Frame_t" />
      <element name="Arena"      type="sai:Arena_t" />
      <element name="Obstacles"  type="sai:ObstacleDatabase_t" />
      <element name="Nodes"      type="sai:NodeGroup_t" />
            
    </sequence>
  </complexType>
</element>
  
</schema>

=== mvsframework/mvs/XML/nodes.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
 /*
 *  Copyright © 2015 Claus Christmann <hcc |ä| gatech.edu>.
 *  
 */
-->
<Configuration
  xmlns="http://uav.ae.gatech.edu/XML/SAI"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://uav.ae.gatech.edu/XML/SAI ../../XSD/sai.xsd"
>

<DatumNED>
  <coordinates>-84.38453231630939,33.759579111458,00.0</coordinates>
</DatumNED>

<Arena>
  <!--  Downtown  -->
<!--  <coordinates>
        -84.38907390071307,33.758287753606,0 -84.38085661618895,33.75827967530952,0 -84.38082092928302,33.7632216919809,0 -84.38919397650393,33.76327330531792,0 -84.38907390071307,33.758287753606,0 
  </coordinates>-->
  
  <!-- Expanded Downtown -->
  <coordinates>
        -84.3929241195227,33.75521764046228,0 -84.37840789102927,33.75521764046228,0 -84.37840789102927,33.76626469298076,0 -84.3929241195227,33.76626469298076,0 -84.3929241195227,33.75521764046228,0 
  </coordinates>

</Arena>

<Obstacles>
  <href>KML/obstacles.kml</href>
</Obstacles>

<Nodes>
  <UAV><!-- Peru0 -->
    <name>Peru0</name>
    <coordinates>-84.38504009447274,33.75961449193584,0</coordinates>
    <startupDelay>1003</startupDelay>
    <dds>
      <name>DDS</name>
    </dds>
    <camera>
      <hFov>80</hFov>
    </camera>
    <gust>
      <name>GUST Interface</name>
      <gustIp>192.168.54.150</gustIp>
      <gustUdpPort>3010</gustUdpPort>
      <localIp>192.168.54.150</localIp>
      <localUdpPort>2010</localUdpPort>
      <inpFilePath>~/svn/work/rmax</inpFilePath>
      <manAugment><!-- using the defaults -->
        <anom />
        <jerk />
        <vcHzGo />
        <vcHzStop />
        <vcHzSide />        
      </manAugment>
      <params_mr>
        <damp />
      </params_mr>
    </gust>
  </UAV>
  <UAV><!-- Peru1 -->
    <name>Peru1</name>
    <coordinates>-84.38608117429675,33.76157948586032,0</coordinates>
    <startupDelay>4011</startupDelay>
    <dds>
      <name>DDS</name>
    </dds>
    <gust>
      <name>GUST Interface</name>
      <gustIp>192.168.54.150</gustIp>
      <gustUdpPort>3040</gustUdpPort>
      <localIp>192.168.54.150</localIp>
      <localUdpPort>2040</localUdpPort>
      <inpFilePath>~/svn/work/rmax</inpFilePath>
      <manAugment><!-- using the defaults -->
        <anom />
        <jerk />
        <vcHzGo />
        <vcHzStop />
        <vcHzSide />        
      </manAugment>
      <params_mr>
        <damp />
      </params_mr>
    </gust>
  </UAV>
  <UAV><!-- Peru2 -->
    <name>Peru2</name>
    <coordinates>-84.38578119065617,33.76028499143538,0</coordinates>
    <startupDelay>5013</startupDelay>
    <dds>
      <name>DDS</name>
    </dds>
    <camera>
      <hFov>80</hFov>
    </camera>
    <gust>
      <name>GUST Interface</name>
      <gustIp>192.168.54.150</gustIp>
      <gustUdpPort>3050</gustUdpPort>
      <localIp>192.168.54.150</localIp>
      <localUdpPort>2050</localUdpPort>
      <inpFilePath>~/svn/work/rmax</inpFilePath>
      <manAugment><!-- using the defaults -->
        <anom />
        <jerk />
        <vcHzGo />
        <vcHzStop />
        <vcHzSide />        
      </manAugment>
      <params_mr>
        <damp />
      </params_mr>
    </gust>
  </UAV>
  <UAV><!-- Peru3 -->
    <name>Peru3</name>
    <coordinates>-84.38609722334994,33.7621742710947,0</coordinates>
    <startupDelay>6017</startupDelay>
    <dds>
      <name>DDS</name>
    </dds>
    <camera>
      <hFov>80</hFov>
    </camera>
    <gust>
      <name>GUST Interface</name>
      <gustIp>192.168.54.150</gustIp>
      <gustUdpPort>3060</gustUdpPort>
      <localIp>192.168.54.150</localIp>
      <localUdpPort>2060</localUdpPort>
      <inpFilePath>~/svn/work/rmax</inpFilePath>
      <manAugment><!-- using the defaults -->
        <anom />
        <jerk />
        <vcHzGo />
        <vcHzStop />
        <vcHzSide />        
      </manAugment>
      <params_mr>
        <damp />
      </params_mr>
    </gust>
  </UAV>
  <UAV><!-- Peru4 -->
    <name>Peru4</name>
    <coordinates>-84.38456511651836,33.75917337933702,0</coordinates>
    <startupDelay>7019</startupDelay>
    <dds>
      <name>DDS</name>
    </dds>
    <camera>
      <hFov>80</hFov>
    </camera>
    <gust>
      <name>GUST Interface</name>
      <gustIp>192.168.54.150</gustIp>
      <gustUdpPort>3070</gustUdpPort>
      <localIp>192.168.54.150</localIp>
      <localUdpPort>2070</localUdpPort>
      <inpFilePath>~/svn/work/rmax</inpFilePath>
      <manAugment><!-- using the defaults -->
        <anom />
        <jerk />
        <vcHzGo />
        <vcHzStop />
        <vcHzSide />        
      </manAugment>
      <params_mr>
        <damp />
      </params_mr>
    </gust>
  </UAV>
  <UAV><!-- Peru5 -->
    <name>Peru5</name>
    <coordinates>-84.38456511651836,33.75917337933702,0</coordinates>
    <startupDelay>8023</startupDelay>
    <dds>
      <name>DDS</name>
    </dds>
    <camera>
      <hFov>80</hFov>
    </camera>
    <gust>
      <name>GUST Interface</name>
      <gustIp>192.168.54.150</gustIp>
      <gustUdpPort>3080</gustUdpPort>
      <localIp>192.168.54.150</localIp>
      <localUdpPort>2080</localUdpPort>
      <inpFilePath>~/svn/work/rmax</inpFilePath>
      <manAugment><!-- using the defaults -->
        <anom />
        <jerk />
        <vcHzGo />
        <vcHzStop />
        <vcHzSide />        
      </manAugment>
      <params_mr>
        <damp />
      </params_mr>
    </gust>
  </UAV>  
  <UAV><!-- Chile0 -->
    <name>Chile0</name>
    <coordinates>-84.38445532212944,33.76085057958649,0</coordinates>
    <startupDelay>2005</startupDelay>
    <dds>
      <name>DDS</name>
    </dds>
    <gust>
      <name>GUST Interface</name>
      <gustIp>192.168.54.150</gustIp>
      <gustUdpPort>3020</gustUdpPort>
      <localIp>192.168.54.150</localIp>
      <localUdpPort>2020</localUdpPort>
      <inpFilePath>~/svn/work/rmax</inpFilePath>
      <manAugment><!-- using the defaults -->
        <anom />
        <jerk />
        <vcHzGo />
        <vcHzStop />
        <vcHzSide />        
      </manAugment>
      <params_mr>
        <damp />
      </params_mr>
    </gust>
  </UAV>
  <UAV><!-- Chile1 -->
    <name>Chile1</name>
    <coordinates>-84.38456511651836,33.75917337933702,0</coordinates>
    <startupDelay>9029</startupDelay>
    <dds>
      <name>DDS</name>
    </dds>
    <camera>
      <hFov>80</hFov>
    </camera>
    <gust>
      <name>GUST Interface</name>
      <gustIp>192.168.54.150</gustIp>
      <gustUdpPort>3090</gustUdpPort>
      <localIp>192.168.54.150</localIp>
      <localUdpPort>2090</localUdpPort>
      <inpFilePath>~/svn/work/rmax</inpFilePath>
      <manAugment><!-- using the defaults -->
        <anom />
        <jerk />
        <vcHzGo />
        <vcHzStop />
        <vcHzSide />        
      </manAugment>
      <params_mr>
        <damp />
      </params_mr>
    </gust>
  </UAV>
  <UAV><!-- Ecuador0 -->
    <name>Ecuador0</name>
    <coordinates>-84.38400446233371,33.76211009231169,0</coordinates>
    <startupDelay>3007</startupDelay>
    <dds>
      <name>DDS</name>
    </dds>
    <gust>
      <name>GUST Interface</name>
      <gustIp>192.168.54.150</gustIp>
      <gustUdpPort>3030</gustUdpPort>
      <localIp>192.168.54.150</localIp>
      <localUdpPort>2030</localUdpPort>
      <inpFilePath>~/svn/work/rmax</inpFilePath>
      <manAugment><!-- using the defaults -->
        <anom />
        <jerk />
        <vcHzGo />
        <vcHzStop />
        <vcHzSide />        
      </manAugment>
      <params_mr>
        <damp />
      </params_mr>
    </gust>
  </UAV>
  <UAV><!-- Ecuador1 -->
    <name>Ecuador1</name>
    <coordinates>-84.38456511651836,33.75917337933702,0</coordinates>
    <startupDelay>10031</startupDelay>
    <dds>
      <name>DDS</name>
    </dds>
    <camera>
      <hFov>80</hFov>
    </camera>
    <gust>
      <name>GUST Interface</name>
      <gustIp>192.168.54.150</gustIp>
      <gustUdpPort>3100</gustUdpPort>
      <localIp>192.168.54.150</localIp>
      <localUdpPort>2100</localUdpPort>
      <inpFilePath>~/svn/work/rmax</inpFilePath>
      <manAugment><!-- using the defaults -->
        <anom />
        <jerk />
        <vcHzGo />
        <vcHzStop />
        <vcHzSide />        
      </manAugment>
      <params_mr>
        <damp />
      </params_mr>
    </gust>
  </UAV>

  
</Nodes>


   
</Configuration>

=== mvsframework/mvs/XML/training/gcs.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
 /*
 *  Copyright © 2015 Claus Christmann <hcc |ä| gatech.edu>.
 *  
 */
-->
<Configuration
  xmlns="http://uav.ae.gatech.edu/XML/SAI"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://uav.ae.gatech.edu/XML/SAI ../../XSD/sai.xsd"
>

<DatumNED>
  <!--  Downtown  -->
 <coordinates>-84.38453231630939,33.759579111458,00.0</coordinates>
  
  <!-- McKenna MOUT -->
<!--   <coordinates>-84.80505663562711,32.37080242806627,00.0</coordinates> -->
</DatumNED>

<Arena>
  <!-- Training grounds in ATL -->
  <coordinates>
    -84.39052716628132,33.75688219359806,0 -84.38150721445373,33.75673721012604,0 -84.38129430284928,33.7619711767231,0 -84.39063195163516,33.76185640311421,0 -84.39052716628132,33.75688219359806,0 
  </coordinates> 
</Arena>

<Obstacles>
  <href>KML/TrainingGrounds.kml</href>
  <!--<href>KML/obstacles.kml</href>-->
  <!--<href>KML/McKenna_MOUT.kml</href> -->
</Obstacles>

<Nodes>
  <ControlStation>
    <name>GCS2</name>
    <!--  Downtown  -->
    <coordinates>-84.38456511651836,33.75917337933702,0</coordinates>
    <!-- McKenna MOUT 
    <coordinates>-84.80505663562711,32.37080242806627,0</coordinates> -->
   
    <startupDelay>0002</startupDelay>
    <dds>
      <name>DDS</name>
    </dds>
    <camera>
      <hFov>120</hFov> <!-- approx. human binocular vision -->
    </camera>
    <hmi>
      <name>HMI</name>
      <Joystick>
        <name>GREAT PLANES InterLink Elite</name>
        <Roll>
          <axis>0</axis>
          <max>24660</max>
          <min>-24999</min>
        </Roll>
        <Pitch>
          <axis>1</axis>
          <max>22633</max>
          <min>-22634</min>
        </Pitch>
        <Yaw>
          <axis>4</axis>
          <max>24998</max>
          <min>-21958</min>
        </Yaw>
        <Throttle>
          <axis>2</axis>
          <reverse /> <!-- use the default value "true" -->
          <max>22971</max>
          <min>-20607</min>
        </Throttle>
        <button action="altitudeHold">0</button>
        <button action="dash">1</button>
        <button action="extremes">2</button>
        <autoRepeatDelay /> <!-- use the default value "250"-->
      </Joystick>
    </hmi>
  </ControlStation>
</Nodes>
   
</Configuration>
